services:
  postgres-db:
    image: postgres:15-alpine
    container_name : investquest-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=investquest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis-cache:
    image: redis:7-alpine
    container_name : investquest-redis
    ports:
      - "6379:6379"
  
  user-service:
    build: ./backend/user-service
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  
volumes:
  postgres_data: